volumes:
  db:
  git:
  vendor:
  idea:

services:
  web:
    image: ghcr.io/nanasess/ec-cube-php:7.2-apache-4.0
    ports:
      - "1080:80"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:password@db:3306/eccube
      - DATABASE_SERVER_VERSION=5.7
      - MAILER_URL=smtp://mail:1025
      - ECCUBE_TIMEZONE=Asia/Tokyo
      - ECCUBE_CURRENCY=JPY
      - ECCUBE_ADMIN_USER=admin
      - ECCUBE_ADMIN_PASS=password
      - ECCUBE_AUTH_MAGIC=change_me
      - ECCUBE_ADMIN_ROUTE=admin
      - ECCUBE_TEMPLATE_CODE=default
      - ECCUBE_LOCALE=ja
      - ECCUBE_PACKAGE_API_URL=http://package:8080      
      - PLUGIN_CODE=UnivaPay
      - ECCUBE_AUTHENTICATION_KEY=test
    volumes:
      - ".:/var/www/html/app/Plugin/UnivaPay"
      - "git:/var/www/html/app/Plugin/UnivaPay/.git"
      - "idea:/var/www/html/app/Plugin/UnivaPay/IDEA"
      - "vendor:/var/www/html/app/vendor"
    depends_on:
      - db
      - package
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost.com:host-gateway"

  package:
    image: eccube/mock-package-api
    environment:
      - MOCK_REPO_DIR=/repos
    ports:
      - "8080:8080"
    volumes:
      - "./dist:/repos"
    networks:
      - backend
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_PORT=3306
    depends_on:
      - db
    networks:
      - backend

  mail:
    image: axllent/mailpit
    ports:
      - "2080:8025"
    networks:
      - backend

networks:
  backend:
    driver: bridge
