name: Lint and Test

on: 
  push:
    branches:
    - master
  pull_request:

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.3, 7.4 ]
        db: [ mysql, pgsql ]
        plugin-code: [ UnivaPay ]
        include:
          - db: mysql
            database_url: mysql://root:root@127.0.0.1:3306/eccube_db
            database_server_version: 5
          - db: pgsql
            database_url: postgres://postgres:password@127.0.0.1:5432/eccube_db
            database_server_version: 14

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout EC-CUBE
      uses: actions/checkout@v4
      with:
        repository: EC-CUBE/ec-cube
        ref: '4.0'

    - name: Checkout EC-CUBE plugin
      uses: actions/checkout@v4
      with:
        path: app/Plugin/${{ matrix.plugin-code }}

    - name: Downgrade composer
      run: sudo composer self-update --1

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Setup PHP
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}

    - name: composer install
      run: |
        curl -O https://getcomposer.org/download/latest-1.x/composer.phar
        php composer.phar install --dev --no-interaction -o --apcu-autoloader

    - name: Setup EC-CUBE and plugin
      env:
        DATABASE_URL: ${{ matrix.database_url }}
        DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
        ECCUBE_LOCALE: ja
      run: |
        bin/console doctrine:database:create
        bin/console doctrine:schema:create
        bin/console eccube:fixtures:load
        bin/console eccube:plugin:install --code ${{ matrix.plugin-code }}
        bin/console eccube:plugin:enable --code ${{ matrix.plugin-code }}

    - name: PHPUnit for plugin
      env:
        APP_ENV: 'test'
        DATABASE_URL: ${{ matrix.database_url }}
        DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
        MAILER_URL: 'smtp://localhost:1025'
      run: |
        bin/phpunit app/Plugin/${{ matrix.plugin-code }}
